;
; File generated by co65 v 2.15 using model `none'
;
.fopt		compiler,"co65 v 2.15"
.case		on
.debuginfo	off

_play = CODE+0
.export	_play
read = CODE+0
.export	read
format = CODE+34
.export	format
loopme = CODE+14
.export	loopme
sizeframe = CODE+35
.export	sizeframe

;
; CODE SEGMENT
;
.segment	"CODE"
CODE:
	.byte	$A9
	.byte	<(CODE-4062)
	.byte	$85
	.byte	$2C
	.byte	$A9
	.byte	>(CODE+34)
	.byte	$85
	.byte	$2D
	.byte	$A9
	.byte	$03
	.byte	$A0
	.byte	$00
	.byte	$00
	.byte	$27
	.byte	$A9
	.byte	$00
	.byte	$85
	.byte	$2C
	.byte	$A9
	.byte	$A0
	.byte	$85
	.byte	$2D
	.byte	$AD
	.word	CODE+35
	.byte	$AC
	.word	CODE+36
	.byte	$00
	.byte	$27
	.byte	$4C
	.word	CODE+14
	.byte	$60
	.byte	$00
	.byte	$00
	.byte	$00

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	0

;
; ZEROPAGE SEGMENT
;
.segment	"ZEROPAGE": zeropage
ZEROPAGE:
	.res	0

.end
