;
; File generated by co65 v 2.15 using model `none'
;
.fopt		compiler,"co65 v 2.15"
.case		on
.debuginfo	off

_play = CODE+0
.export	_play
read = CODE+0
.export	read
format = BSS+0
.export	format
loopme = CODE+14
.export	loopme
sizeframe = BSS+6
.export	sizeframe
next = CODE+30
.export	next
end = CODE+33
.export	end
number_of_frames = BSS+4
.export	number_of_frames

;
; CODE SEGMENT
;
.segment	"CODE"
CODE:
	.byte	$A9
	.byte	<(BSS-16384)
	.byte	$85
	.byte	$2C
	.byte	$A9
	.byte	>(BSS+0)
	.byte	$85
	.byte	$2D
	.byte	$A9
	.byte	$08
	.byte	$A0
	.byte	$00
	.byte	$00
	.byte	$27
	.byte	$A9
	.byte	$00
	.byte	$85
	.byte	$2C
	.byte	$A9
	.byte	$A0
	.byte	$85
	.byte	$2D
	.byte	$AD
	.word	BSS+6
	.byte	$AC
	.word	BSS+7
	.byte	$00
	.byte	$27
	.byte	$4C
	.word	CODE+14
	.byte	$60

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	8

;
; ZEROPAGE SEGMENT
;
.segment	"ZEROPAGE": zeropage
ZEROPAGE:
	.res	0

.end
